// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC4MX-hQl--i9J9T891WhwYtDkQvmcvo0',
    appId: '1:409123346496:web:8ade683d1e99132ecde7a5',
    messagingSenderId: '409123346496',
    projectId: 'fir-people-287b2',
    authDomain: 'fir-people-287b2.firebaseapp.com',
    storageBucket: 'fir-people-287b2.firebasestorage.app',
    measurementId: 'G-N06DVGWYTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfbEZKicsWIkTElVQ_UrJBpGqMAruQybA',
    appId: '1:409123346496:android:456b927cb675b5cfcde7a5',
    messagingSenderId: '409123346496',
    projectId: 'fir-people-287b2',
    storageBucket: 'fir-people-287b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR9215Q4-69oaM3ijqIjmUpSvzbfx_zi4',
    appId: '1:409123346496:ios:4f13390bc7e140e9cde7a5',
    messagingSenderId: '409123346496',
    projectId: 'fir-people-287b2',
    storageBucket: 'fir-people-287b2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR9215Q4-69oaM3ijqIjmUpSvzbfx_zi4',
    appId: '1:409123346496:ios:4f13390bc7e140e9cde7a5',
    messagingSenderId: '409123346496',
    projectId: 'fir-people-287b2',
    storageBucket: 'fir-people-287b2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC4MX-hQl--i9J9T891WhwYtDkQvmcvo0',
    appId: '1:409123346496:web:07373d0f10f4afbacde7a5',
    messagingSenderId: '409123346496',
    projectId: 'fir-people-287b2',
    authDomain: 'fir-people-287b2.firebaseapp.com',
    storageBucket: 'fir-people-287b2.firebasestorage.app',
    measurementId: 'G-NVVM7T6K31',
  );
}
